#!/usr/bin/env python3
"""
Extract emoji from a custom atlas and save as CSV.
Uses emoji_positions_map.txt to find where each emoji is located in the atlas.
"""

import sys
import os
from PIL import Image
import numpy as np


def sanitize_emoji_name(name):
    """Sanitize emoji name for comparison."""
    sanitized = ""
    for char in name.lower():
        if char.isalnum() or char in ['_', '-']:
            sanitized += char
        else:
            sanitized += '_'
    return sanitized


def extract_emoji_from_custom_atlas(atlas_path, parsed_emojis_path, emoji_name, output_dir):
    """
    Extract a specific emoji from a custom atlas based on its name.
    Uses emoji_positions_map.txt to find where each emoji is located in the atlas.
    
    Args:
        atlas_path: Path to the custom emoji atlas PNG
        parsed_emojis_path: Path to parsed_emojis.txt (not used in this version, kept for compatibility)
        emoji_name: Name of the emoji to extract
        output_dir: Output directory for the CSV file
    """
    # Read the emoji_positions_map.txt to find where the requested emoji is located
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))  # Get the directory of the current script
    emoji_positions_file = os.path.join(script_dir, 'emoji_positions_map.txt')
    
    try:
        with open(emoji_positions_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: {emoji_positions_file} not found. Map file should be generated by the atlas creator.")
        return False
    
    # Find the requested emoji in the map
    emoji_index = None
    for line in lines:
        if line.strip() and not line.startswith('#'):
            parts = line.strip().split('|')
            if len(parts) >= 3:
                mapped_emoji_name = parts[0]  # Full name as stored in map
                # Check if the requested emoji matches this entry (using sanitization for comparison)
                mapped_sanitized = sanitize_emoji_name(mapped_emoji_name)
                requested_sanitized = sanitize_emoji_name(emoji_name)
                
                # Check for exact match or substring match
                if (mapped_sanitized == requested_sanitized or 
                    requested_sanitized == mapped_sanitized or
                    requested_sanitized in mapped_sanitized or
                    mapped_sanitized in requested_sanitized):
                    emoji_index = int(parts[1])  # Position index
                    break
    
    if emoji_index is None:
        print(f"Error: Emoji '{emoji_name}' not found in position map. Available emojis in map:")
        for line in lines:
            if line.strip() and not line.startswith('#'):
                parts = line.strip().split('|')
                if len(parts) >= 3:
                    print(f"  - {parts[0]} (index {parts[1]})")
        return False
    
    print(f"Found emoji '{emoji_name}' at position {emoji_index} in atlas")
    
    # Load the atlas image
    try:
        atlas_img = Image.open(atlas_path)
        atlas_width, atlas_height = atlas_img.size
        atlas_array = np.array(atlas_img)
    except Exception as e:
        print(f"Error loading atlas image {atlas_path}: {e}")
        return False
    
    # Calculate emoji size based on atlas width
    total_emojis_in_atlas = atlas_width // atlas_height  # Assuming square emoji size = atlas_height
    emoji_size = atlas_height  # Each emoji is full height of atlas
    
    if emoji_index >= total_emojis_in_atlas:
        print(f"Error: Requested emoji index {emoji_index} exceeds emojis in atlas ({total_emojis_in_atlas})")
        return False
    
    # Extract the emoji from the atlas
    start_x = emoji_index * emoji_size
    end_x = start_x + emoji_size
    
    # Crop the emoji region from the atlas
    emoji_region = atlas_array[:, start_x:end_x, :]  # y, x, channels
    
    # Verify we got a valid region
    if emoji_region.shape[0] != emoji_size or emoji_region.shape[1] != emoji_size:
        print(f"Error: Could not extract emoji at index {emoji_index}, region shape: {emoji_region.shape}")
        return False
    
    # Create the output directory if it doesn't exist
    os.makedirs(os.path.join(output_dir, emoji_name), exist_ok=True)
    output_path = os.path.join(output_dir, emoji_name, f"{emoji_name}.csv")
    
    # Downscale the emoji to 8x8
    from PIL import Image as PILImage
    emoji_img = PILImage.fromarray(emoji_region.astype(np.uint8))
    # Use a high-quality resampling filter for better results
    emoji_8x8 = emoji_img.resize((8, 8), PILImage.LANCZOS)  # Use LANCZOS for good quality
    
    # Write the 8x8 emoji to CSV
    with open(output_path, 'w', encoding='utf-8') as f:
        for y in range(8):
            row = []
            for x in range(8):
                pixel = emoji_8x8.getpixel((x, y))
                # Handle different image modes (RGB, RGBA, etc.)
                if isinstance(pixel, (tuple, list)):
                    if len(pixel) >= 3:
                        r, g, b = pixel[:3]  # Take first 3 values (R, G, B)
                    else:
                        r = g = b = pixel[0]  # Grayscale
                else:
                    # Single value (grayscale)
                    r = g = b = pixel
                
                row.append(f'"{r},{g},{b}"')
            f.write(','.join(row) + '\n')
    
    print(f"Successfully extracted {emoji_name} from custom atlas and saved to {output_path}")
    return True


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <custom_atlas.png> <parsed_emojis.txt> <emoji_name>")
        sys.exit(1)
    
    atlas_path = sys.argv[1]
    parsed_emojis_path = sys.argv[2]
    emoji_name = sys.argv[3]
    
    # Output to current working directory
    success = extract_emoji_from_custom_atlas(atlas_path, parsed_emojis_path, emoji_name, os.getcwd())
    
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()