// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TSOTSrpg_core","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_managers","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_objects","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_scenes","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_sprites","status":true,"description":"","parameters":{}},
{"name":"console boot","status":true,"description":"Shows the developer console on boot.","parameters":{"Console Width":"800","Console Height":"300","Console X-Position":"0","Console Y-Position":"0","Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}}
];
