name: Build

on:
  push:
    paths-ignore:
        - '.gitignore'
        - 'docs/*'
        - 'syntax/*'
        - 'themes/*'
        - 'README.md'

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Prepare directories
        run: make prep

      - name: Build release
        run: make release

      - name: Build debug
        run: make debug

      - name: Archive release binary
        uses: actions/upload-artifact@v3
        with:
          name: nino-linux
          path: release/nino

  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare directories
        run: make prep

      - name: Build release
        run: make release

      - name: Build debug
        run: make debug

      - name: Archive release binary
        uses: actions/upload-artifact@v3
        with:
          name: nino-windows
          path: release/nino.exe
